import { describe, expect, it } from "vitest";
import { serviceSales, serviceSalesUi } from "./serviceSales";
import { getServiceBySlug } from "./services";
import { getCaseBySlug } from "./cases";
import { stripEmphasis } from "@/components/ui/RichText";

const coreExpected = {
  id: "core", contactHref: "/uslugi/systemy-i-integracje/#contact",
  hero: { eyebrow: "Systemy i integracje", h1: "Połącz ERP, sklep i pozostałe systemy. Bez ręcznego przepisywania danych.", lead: "Integruję Comarch, Subiekt, enova i systemy e-commerce tak, żeby zamówienia, stany, ceny, dokumenty i faktury przepływały między nimi bez rozjazdów i ręcznych poprawek.", note: "Nie musisz przygotowywać specyfikacji technicznej. Napisz, z jakich systemów korzystasz i gdzie dziś pojawiają się błędy albo ręczna praca.", cta: "Sprawdźmy, jak połączyć Twoje systemy" },
  problems: { title: "Co przestaje być problemem po dobrej integracji", items: [
    { title: "Ręczne przepisywanie zamówień", body: "Zamówienie przechodzi ze sklepu lub marketplace do ERP bez ponownego wpisywania tych samych danych." },
    { title: "Różne ceny i stany w różnych kanałach", body: "Zmiana w systemie źródłowym trafia tam, gdzie jest potrzebna, zamiast czekać na kolejną ręczną aktualizację." },
    { title: "Dokumenty zatrzymane między systemami", body: "Faktury, dokumenty magazynowe i dane kontrahentów przechodzą ustaloną ścieżką, z informacją o tym, co wymaga reakcji." },
    { title: "Błędy ukryte w logach", body: "Wyjątki trafiają do obsługi zamiast znikać w technicznym komunikacie, którego nikt na co dzień nie sprawdza." },
  ] },
  systems: { title: "Łączę systemy, które już działają w Twojej firmie", intro: "Nie zaczynam od wymiany narzędzi, które spełniają swoją rolę. Najpierw sprawdzam, jak bezpiecznie połączyć to, co już masz.", items: [
    { title: "ERP i systemy handlowe", body: "Comarch ERP Optima i XL — towary, ceny, zamówienia oraz dokumenty magazynowe.\nSubiekt GT i nexo — stany, ceny i zamówienia między Subiektem a kanałami sprzedaży.\nenova365 — kontrahenci, dokumenty handlowe i rozrachunki.\nWAPRO Mag i Symfonia — zakres dobrany do wersji i możliwości wymiany danych." },
    { title: "Sklepy i marketplace", body: "WooCommerce i PrestaShop — produkty, warianty, stany, ceny, zamówienia i faktury.\nAllegro — oferty, zamówienia i wiadomości z uwzględnieniem ograniczeń platformy.\nBaseLinker — połączenie istniejącej konfiguracji z ERP bez wymiany narzędzia tylko dla zasady." },
    { title: "Dokumenty i wymiana danych", body: "KSeF — wystawianie, odbiór i obsługa błędów tam, gdzie gotowy moduł producenta nie wystarcza.\nEDI i systemy partnerów — wymiana dokumentów i danych w formatach wymaganych przez drugą stronę.\nStarsze systemy — także wtedy, gdy dostępna jest wymiana przez pliki, bazę lub FTP zamiast nowoczesnego API." },
  ], cta: "Pokaż, gdzie dziś rozjeżdżają się dane" },
  proof: { caseSlugs: ["public-sector-poland", "public-sector-eu"], title: "Systemy, w których nie ma miejsca na „prawie działa”", cta: "Porozmawiajmy o Twojej integracji" },
  scope: { title: "Co mogę połączyć i uporządkować", bullets: ["przepływ zamówień między sklepem, marketplace, magazynem i ERP;", "synchronizację stanów, cen, produktów i danych kontrahentów;", "faktury, dokumenty magazynowe, KSeF i wymianę z partnerami;", "migracje danych z kontrolą kompletności;", "obsługę błędów, ponawianie operacji i czytelną ścieżkę tego, co wydarzyło się z danym zamówieniem lub dokumentem."] },
  process: { title: "Najpierw jeden ważny przepływ, potem reszta", steps: [
    { title: "Pokazujesz obecną drogę danych", body: "Ustalamy, które systemy biorą udział w procesie, gdzie powstają błędy i co dziś wymaga ręcznej pracy." },
    { title: "Sprawdzam realne możliwości", body: "Weryfikuję wersje, licencje, dostępne interfejsy i ograniczenia. Dopiero na tej podstawie określam zakres." },
    { title: "Uruchamiam najmniejszy wartościowy przepływ", body: "Zaczynam od fragmentu, który może najszybciej zdjąć ręczną pracę albo ograniczyć kosztowne pomyłki." },
    { title: "Zabezpieczam wyjątki i rozszerzam integrację", body: "Dodaję monitoring, obsługę błędów oraz kolejne kierunki wymiany danych bez zatrzymywania działającego procesu." },
  ] },
  demos: [{ slug: "puls", body: "Sklep, marketplace i ERP — jedna wersja prawdy. Panel pokazuje stan kanałów, drogę zamówienia oraz wyjątki, które naprawdę wymagają decyzji.", cta: "Zobacz Puls" }, { slug: "airlift", body: "Kontrola dużej migracji danych: postęp, możliwość wznowienia i potwierdzenie, że przeniesione dane są kompletne.", cta: "Zobacz AIRLIFT" }],
  pricing: { title: "Skąd bierze się wycena", body: "Nie wyceniam integracji na podstawie samej liczby systemów. Znaczenie mają kierunki przepływu danych, możliwości konkretnych wersji, liczba wyjątków, wymagany czas reakcji i sposób bezpiecznego uruchomienia. Najpierw sprawdzam te ograniczenia, potem opisuję zakres i wycenę.", cta: "Zobacz, jak rozliczam projekty →" },
  technology: { title: "Szczegóły techniczne dla zainteresowanych", body: "Korzystam z oficjalnych API, REST, SOAP, kolejek, EDI oraz wymiany plikowej — zależnie od tego, co rzeczywiście udostępniają systemy. Tam, gdzie przepływ ma znaczenie finansowe lub prawne, projektuję ponawianie operacji, kontrolę spójności, historię zdarzeń i bezpieczny sposób przełączenia." },
  faq: [
    { question: "Jak szybko można uruchomić pierwszy działający fragment?", answer: "Zależy to przede wszystkim od dostępu do systemów i jakości ich interfejsów. Zamiast czekać na całość, wybieram jeden przepływ o największej wartości i po weryfikacji możliwości rozpisuję jego pierwsze wdrożenie." },
    { question: "Czy do integracji trzeba dokładać wiele nowych narzędzi?", answer: "Nie z założenia. Najpierw wykorzystuję możliwości systemów, które już działają w firmie. Nowy element dokładam tylko wtedy, gdy upraszcza przepływ albo jest potrzebny do jego bezpiecznej obsługi." },
    { question: "Skąd mam wiedzieć, że wycena nie jest sztucznie zawyżona?", answer: "Wycena wynika z opisanych przepływów, ograniczeń systemów i zakresu obsługi wyjątków. Dostajesz informację, co wpływa na koszt. Jeśli wystarczy gotowy moduł producenta albo prostsza zmiana procesu, mówię o tym przed rozpoczęciem prac. Zobacz także cennik." },
    { question: "Czy wdrożenie zatrzyma sprzedaż albo pracę ERP?", answer: "Nie zakładam tego w ciemno. Najpierw sprawdzam możliwości środowiska, przygotowuję próby poza produkcją oraz sposób przełączenia i powrotu. Ewentualne ograniczenia lub potrzebne okno serwisowe są znane przed wdrożeniem." },
    { question: "Co jeśli system nie ma dobrego API?", answer: "Sprawdzam oficjalnie wspierane możliwości: pliki, bazę, moduły dodatkowe albo inne kanały wymiany. Jeśli jedyna dostępna droga byłaby zbyt krucha lub nieopłacalna, nie ukrywam tego w wycenie." },
    { question: "Co dzieje się, gdy jeden z systemów przestaje odpowiadać?", answer: "Integracja nie powinna po prostu zgubić danych. Dobieram sposób ponawiania, zapisu stanu i zgłaszania wyjątków do znaczenia procesu oraz możliwości obu systemów." },
  ],
  demosTitle: "Zobacz, jak może wyglądać obsługa integracji", faqTitle: "FAQ",
  contact: { title: "Sprawdźmy, gdzie dziś uciekają dane i czas", intro: "Nie musisz znać API ani przygotowywać dokumentacji technicznej. Opisz krótko, które systemy mają wymieniać dane i co dziś nie działa. Wrócę z informacją, czy mogę pomóc i jaki widzę następny krok.", checks: ["najpierw sprawdzam możliwości systemów, dopiero potem określam zakres;", "jeśli gotowy moduł producenta wystarczy, mówię o tym wprost;", "możesz zacząć od jednego przepływu zamiast przebudowywać wszystko naraz."], calendlyTitle: "Wolisz pokazać przepływ na rozmowie?", calendlyBody: "Umów bezpłatne 30 minut. Możesz opowiedzieć, z jakich systemów korzystasz i w którym miejscu dane przestają się zgadzać.", calendlyCta: "Umów rozmowę o integracji", form: { title: "Opisz, co ma się połączyć", intro: "Nazwy systemów i jedno zdanie o problemie wystarczą na start.", messageLabel: "Które systemy mają wymieniać dane i co dziś wymaga ręcznej pracy?", messagePlaceholder: "Na przykład: zamówienia z WooCommerce trafiają do Subiekta, ale stany i ceny często się rozjeżdżają.", submit: "Wyślij opis integracji" }, cta: "Opisz systemy i sprawdź możliwy zakres", stickyCta: "Sprawdź integrację" },
} as const;

const automationExpected = {
  id: "automation", contactHref: "/uslugi/automatyzacja/#contact",
  hero: { eyebrow: "Automatyzacja procesów", h1: "Automatyzuję powtarzalną pracę, która zabiera czas Twojemu zespołowi", lead: "Faktury, dokumenty, raportowanie, onboarding, wiadomości i przepisywanie danych między systemami. Zaczynam od jednego procesu, sprawdzam, ile pracy można odzyskać, i dopiero wtedy proponuję wdrożenie.", note: "Nie zaczynam od narzędzia. Najpierw sprawdzamy, czy automatyzacja w ogóle się opłaca.", cta: "Pokaż proces do automatyzacji" },
  candidates: { title: "Od czego najczęściej warto zacząć", items: [
    { title: "Faktury", body: "Dane z załącznika lub skanu trafiają do dalszej obsługi, a człowiek sprawdza wynik zamiast przepisywać dokument." }, { title: "Obieg dokumentów", body: "Akceptacje, wersje i terminy przechodzą ustaloną ścieżką, bez szukania ostatniej wersji po mailach i komunikatorach." }, { title: "Raportowanie", body: "Raport powstaje z aktualnych danych według harmonogramu, zamiast zabierać zespołowi kolejny koniec miesiąca." }, { title: "Onboarding", body: "Konta, uprawnienia i zadania startowe uruchamia jeden formularz, a nie seria ręcznych przypomnień." }, { title: "Ofertowanie", body: "Dane do oferty pochodzą z właściwego źródła, a handlowiec skupia się na decyzji i rozmowie z klientem." }, { title: "Zamówienia", body: "Informacje przechodzą między sklepem, magazynem i ERP, a do człowieka trafiają tylko sytuacje wymagające decyzji." },
  ] },
  proof: { title: "Dowód z codziennej pracy", caseSlugs: ["localhost-academy"], cta: "Sprawdźmy, ile pracy można odzyskać" },
  criteria: { title: "Nie każda powtarzalna czynność powinna być automatyzowana", intro: "Najpierw sprawdzam cztery rzeczy:", bullets: ["jak często proces się powtarza;", "ile czasu i poprawek kosztuje dzisiaj;", "czy ma jasne reguły i dostępne dane;", "które wyjątki nadal wymagają decyzji człowieka.", "Jeżeli prostsza zmiana procesu rozwiąże problem taniej, rekomenduję ją zamiast budowania automatyzacji."] },
  scope: { title: "Co mogę zrobić", items: [
    { title: "Mapowanie procesu", body: "Rozpisuję faktyczny przebieg pracy, punkty decyzyjne i miejsca, w których uciekają godziny." }, { title: "Połączenie używanych systemów", body: "CRM, ERP, poczta, formularze, dokumenty i płatności wymieniają dane bez ręcznego kopiowania." }, { title: "Automatyzacja powtarzalnych kroków", body: "System wykonuje rutynowe operacje, a zespół zajmuje się wyjątkami i decyzjami." }, { title: "Kontrola człowieka tam, gdzie jest potrzebna", body: "Akceptacje i decyzje biznesowe pozostają po stronie ludzi zamiast znikać w nieprzejrzystym mechanizmie." }, { title: "Raportowanie i obsługa błędów", body: "Widać, co zostało wykonane, co się nie udało i co wymaga reakcji." },
  ] },
  process: { title: "Jeden proces, widoczny efekt, dopiero potem kolejny", steps: [
    { title: "Wybieramy proces", body: "Szukamy pracy, która często się powtarza, zabiera zauważalny czas i ma czytelny początek oraz koniec." }, { title: "Mierzymy punkt wyjścia", body: "Ustalamy, ile czasu zajmuje proces, gdzie pojawiają się błędy i po czym poznamy, że zmiana ma sens." }, { title: "Uruchamiam najmniejszy wartościowy zakres", body: "Automatyzuję najważniejszy fragment bez budowania dużej platformy na zapas." }, { title: "Sprawdzamy wynik i decydujemy o rozszerzeniu", body: "Porównujemy efekt z punktem wyjścia. Kolejny etap powstaje tylko wtedy, gdy dane uzasadniają dalszą inwestycję." },
  ] },
  demos: [{ slug: "cadence", body: "Jeden panel pokazuje działające przepływy, ich ostatnie wyniki, historię uruchomień i alerty. Dzięki temu automatyzacja nie staje się niewidzialnym procesem, o którego awarii firma dowiaduje się od klienta.", cta: "Zobacz Cadence" }],
  pricing: { title: "Skąd bierze się wycena", body: "Koszt zależy od liczby kroków i systemów, jakości dostępnych danych, liczby wyjątków, wymaganej kontroli człowieka oraz kosztów licencji i utrzymania. Wycena opisuje konkretny proces i mierzalny zakres — nie ogólną obietnicę „automatyzacji firmy”.", cta: "Zobacz, jak rozliczam projekty →" },
  technology: { title: "Na czym buduję", intro: "Narzędzie dobieram do procesu, danych i skali. Nie dokładam nowej platformy, jeśli istniejące środowisko wystarczy.", body: "n8n — gdy potrzebna jest większa kontrola, własna infrastruktura albo bardziej złożona logika.\nMake.com — do szybkiego uruchomienia procesów o umiarkowanej skali.\nPower Automate — gdy firma pracuje głównie w Microsoft 365, Teams i SharePoint.\nZapier — do prostych połączeń, jeśli jego ograniczenia i koszty pasują do skali.\nWłasny kod — gdy gotowe narzędzia nie radzą sobie z wolumenem, wyjątkami lub wymaganiami.\nRPA — gdy używany system nie udostępnia rozsądnego sposobu integracji." },
  faq: [
    { question: "Jak szybko można zobaczyć pierwszą wartość?", answer: "Zależy to od procesu i dostępu do danych. Zaczynam od najmniejszego fragmentu, który może ograniczyć ręczną pracę albo liczbę błędów. Termin tego etapu określam po krótkim rozpoznaniu, zamiast obiecywać go przed zobaczeniem procesu." }, { question: "Czy automatyzacja wymaga wielu nowych technologii?", answer: "Nie. Najpierw sprawdzam narzędzia, z których firma już korzysta. Nowy element dokładam tylko wtedy, gdy upraszcza rozwiązanie lub pozwala bezpiecznie osiągnąć potrzebny efekt." }, { question: "Skąd mam wiedzieć, że wycena nie jest sztucznie zawyżona?", answer: "Zakres jest rozpisany dla konkretnego procesu, jego wyjątków i integracji. Widać, co wpływa na koszt wdrożenia i utrzymania. Jeżeli problem można rozwiązać prostszą zmianą procesu, mówię o tym przed rozpoczęciem prac. Zobacz także cennik." }, { question: "Który proces najlepiej zautomatyzować jako pierwszy?", answer: "Taki, który często się powtarza, ma jasne reguły, zabiera zauważalny czas i nie wymaga ludzkiej decyzji na każdym kroku. Nie zawsze jest to najbardziej irytujące zadanie — wybór powinien wynikać z wartości i wykonalności." }, { question: "Co się stanie, gdy proces lub jeden z systemów się zmieni?", answer: "Automatyzacja potrzebuje czytelnej historii działania, zgłaszania błędów i miejsca na zmianę reguł. Zakres utrzymania zależy od użytych systemów i ustalam go przed wdrożeniem." }, { question: "Czy automatyzacja oznacza zastępowanie ludzi albo użycie AI?", answer: "Nie. Celem jest zdjęcie z zespołu powtarzalnej pracy. AI stosuję tylko tam, gdzie ma uzasadnienie, a decyzje wymagające odpowiedzialności lub oceny mogą pozostać po stronie człowieka." },
  ],
  demosTitle: "Zobacz, jak można kontrolować automatyzacje", faqTitle: "FAQ",
  contact: { title: "Pokaż pracę, której zespół nie powinien wykonywać ręcznie", intro: "Nie musisz wiedzieć, jak ją zautomatyzować ani wybierać narzędzia. Opisz krótko, co dzieje się dziś, jak często i co zabiera najwięcej czasu. Wrócę z informacją, czy widzę sens automatyzacji i jaki powinien być następny krok.", checks: ["zaczynam od jednego procesu i konkretnego punktu wyjścia;", "dobieram najprostsze narzędzie, które spełnia wymagania;", "jeśli automatyzacja się nie opłaca, mówię o tym przed wyceną."], calendlyTitle: "Wolisz przejść przez proces na rozmowie?", calendlyBody: "Umów bezpłatne 30 minut. Opowiesz, jak zespół pracuje dzisiaj, a ja pomogę wskazać fragment warty dalszego sprawdzenia.", calendlyCta: "Umów rozmowę o automatyzacji", form: { title: "Opisz jeden powtarzalny proces", intro: "Jedno lub dwa zdania wystarczą. Nie potrzebujesz gotowej mapy procesu.", messageLabel: "Co zespół robi ręcznie i jak często to się powtarza?", messagePlaceholder: "Na przykład: co tydzień zbieramy dane z trzech arkuszy i ręcznie przygotowujemy raport dla zarządu.", submit: "Wyślij opis procesu" }, cta: "Zacznij od jednego procesu", stickyCta: "Pokaż proces" },
} as const;

const webExpected = {
  id: "web", contactHref: "/uslugi/platformy-webowe/#contact",
  hero: { eyebrow: "Aplikacje i platformy webowe", h1: "Aplikacja webowa dopasowana do tego, jak działa Twój biznes", lead: "Portal klienta, panel pracowników, system rezerwacji albo własny produkt online. Od pomysłu i projektu po wdrożenie, z jednym spójnym zakresem i bez budowania funkcji, których nikt nie potrzebuje.", note: "Nie musisz mieć gotowej specyfikacji. Wystarczy cel biznesowy, problem do rozwiązania albo proces, który dziś nie mieści się w gotowych narzędziach.", cta: "Porozmawiajmy o Twojej aplikacji" },
  demosIntro: "Poniższe dema to klikalne propozycje interfejsów i procesów, nie gotowe produkty ani zrzuty wdrożeń klientów. Pokazują sposób myślenia o aplikacji od strony użytkownika i codziennej pracy.", demos: [
    { slug: "merdi", body: "Umawianie wizyt, konto klienta i historia opieki nad zwierzęciem w jednym spokojnym przepływie.", cta: "Zobacz demo Merdi" }, { slug: "vitalab", body: "Badania, wizyty, punkty pobrań i wyniki dostępne z jednego konta pacjenta.", cta: "Zobacz demo VitaLab" }, { slug: "primavita", body: "Wyszukiwanie specjalisty, czytelny cennik i rezerwacja wizyty bez kolejki telefonicznej.", cta: "Zobacz demo Primavita" }, { slug: "healthlab", body: "Panel personelu, który prowadzi zlecenie od przyjęcia do wydania wyniku.", cta: "Zobacz demo HealthLab" }, { slug: "merdi-panel", body: "Kalendarz, plan dnia i kartoteki dostępne w jednym miejscu dla całego personelu.", cta: "Zobacz demo Merdi Panel" },
  ],
  appTypes: { title: "Co można uporządkować jedną aplikacją", items: [
    { title: "Portal klienta", body: "Klient widzi swoją historię, dokumenty, wizyty albo wyniki bez kontaktowania się z obsługą w każdej sprawie." }, { title: "Panel pracowników", body: "Zespół pracuje na jednym widoku procesu zamiast łączyć arkusze, wiadomości i pamięć poszczególnych osób." }, { title: "Rezerwacje i umawianie", body: "Użytkownik przechodzi przez prowadzony proces o dowolnej porze, a firma dostaje komplet potrzebnych danych." }, { title: "Sklep i obsługa zamówienia", body: "Witryna, koszyk, płatność, magazyn i ERP tworzą jeden przepływ zamiast kilku osobnych narzędzi." }, { title: "Narzędzie wewnętrzne", body: "Proces dopasowany do sposobu pracy firmy zastępuje arkusz, który dawno przestał wystarczać." }, { title: "Własny produkt online", body: "Pomysł przechodzi od sprawdzenia założeń do działającej wersji, którą można pokazać użytkownikom i rozwijać na podstawie ich reakcji." },
  ] },
  proof: { title: "Dowody z działających systemów", caseSlugs: ["international-automotive-sales-platform", "enterprise-30-years-in-production"], cta: "Pokaż, co chcesz zbudować" },
  scope: { title: "Co obejmuje projekt", items: [
    { title: "Kierunek produktu i UX", body: "Porządkuję cel, użytkowników i najważniejsze przepływy, zanim powstanie kosztowny kod." }, { title: "Interfejs i logika działania", body: "Frontend i backend powstają jako jedno rozwiązanie, a nie dwa osobne projekty składane na końcu." }, { title: "Płatności i integracje", body: "Aplikacja może łączyć się z CRM, ERP, płatnościami i systemami partnerów." }, { title: "Testy i bezpieczeństwo", body: "Najważniejsze scenariusze są sprawdzane w trakcie prac, a nie odkładane na ostatni etap." }, { title: "Wdrożenie i działanie na produkcji", body: "Projekt obejmuje sposób publikacji, monitorowania i dalszego rozwijania rozwiązania." },
  ] },
  deliverables: ["uzgodniony cel, priorytety i zakres pierwszej wersji;", "zaprojektowane najważniejsze ekrany i przepływy;", "działającą aplikację połączoną z potrzebnymi systemami;", "testy kluczowych scenariuszy i przygotowane wdrożenie;", "czytelnie opisane kolejne kroki, bez dokładania funkcji na zapas."], deliverablesTitle: "Co dostajesz",
  process: { title: "Najpierw najważniejszy przepływ, potem kolejne funkcje", steps: [
    { title: "Ustalamy cel i pierwszych użytkowników", body: "Rozdzielamy to, co jest potrzebne do osiągnięcia pierwszego efektu, od pomysłów, które mogą poczekać." }, { title: "Pokazuję rozwiązanie przed kosztownym wdrożeniem", body: "Najważniejsze ekrany i przepływy można ocenić, zanim cały zakres zostanie zapisany w kodzie." }, { title: "Buduję w widocznych etapach", body: "Każda iteracja kończy się działającym fragmentem, który można sprawdzić i skorygować." }, { title: "Uruchamiam i rozwijam na podstawie użycia", body: "Po wdrożeniu kolejne decyzje wynikają z realnego działania produktu, a nie z listy życzeń przygotowanej na początku." },
  ] },
  pricing: { title: "Skąd bierze się wycena", body: "Na koszt wpływa liczba ról i przepływów, zakres integracji, wymagania bezpieczeństwa, istniejące materiały oraz to, co naprawdę musi znaleźć się w pierwszej wersji. Najpierw oddzielam zakres potrzebny do dostarczenia wartości od funkcji, które mogą powstać później.", cta: "Zobacz, jak rozliczam projekty →" }, technology: { title: "Na czym buduję", intro: "Technologię dobieram do produktu, obecnego środowiska i planowanej skali. Celem nie jest długi stack, tylko rozwiązanie, które można bezpiecznie rozwijać.", body: "Frontend: Angular, React i Next.js.\nBackend: Nest.js, Fastify i Spring Boot.\nDane: PostgreSQL albo MySQL — również wtedy, gdy sensowniejsze jest pozostanie przy bazie, którą firma już ma.\nWdrożenie: automatyzacja publikacji, monitoring i infrastruktura dobrana do realnego ruchu." },
  faq: [
    { question: "Jak szybko można pokazać pierwszą działającą część?", answer: "Zależy to od produktu, ale nie trzeba czekać na cały zakres. Najpierw wybieram najważniejszy przepływ użytkownika i rozpisuję pierwszą wersję tak, żeby można ją było ocenić przed budową pozostałych funkcji." }, { question: "Czy aplikacja musi składać się z wielu technologii?", answer: "Nie. Wybieram najprostszą architekturę, która spełnia wymagania i pozwala rozwijać produkt. Każdy dodatkowy element musi mieć uzasadnienie w bezpieczeństwie, skali albo utrzymaniu." }, { question: "Skąd mam wiedzieć, że wycena nie jest sztucznie zawyżona?", answer: "Zakres pierwszej wersji jest oddzielony od funkcji, które mogą poczekać. Widać, które przepływy, integracje i wymagania wpływają na koszt. Zmiana zakresu jest decyzją, a nie ukrytym dodatkiem do faktury. Zobacz także cennik." }, { question: "Czy potrzebuję gotowej specyfikacji i projektu graficznego?", answer: "Nie. Możesz przyjść z celem biznesowym, opisem problemu albo istniejącym procesem. Jeżeli masz już projekt interfejsu, mogę wykorzystać go jako punkt wyjścia." }, { question: "Kiedy lepiej wybrać gotowy system zamiast budować własny?", answer: "Gdy gotowe narzędzie obsługuje najważniejsze procesy bez kosztownych obejść. Własna aplikacja ma sens wtedy, gdy sposób pracy firmy, integracje lub doświadczenie klienta rzeczywiście wymagają rozwiązania dopasowanego." }, { question: "Czy aplikację można rozwijać po pierwszym wdrożeniu?", answer: "Tak — dlatego pierwsza wersja powinna obejmować najważniejszy przepływ i przygotować miejsce na świadome rozszerzenia. Nie oznacza to jednak budowania całej przyszłej architektury na zapas." },
  ],
  demosTitle: "Zobacz, jak może działać Twoje rozwiązanie", faqTitle: "FAQ",
  contact: { title: "Zacznij od problemu, nie od specyfikacji", intro: "Opisz krótko, co użytkownik albo pracownik powinien móc zrobić łatwiej niż dzisiaj. Wrócę z informacją, czy lepsza będzie własna aplikacja, prostsze gotowe narzędzie czy jeszcze inny następny krok.", checks: ["pierwszą wersję ograniczam do funkcji potrzebnych do osiągnięcia celu;", "technologia wynika z produktu, nie z mody;", "zakres i elementy wpływające na wycenę są widoczne przed rozpoczęciem prac."], calendlyTitle: "Wolisz omówić pomysł na żywo?", calendlyBody: "Umów bezpłatne 30 minut. Nie potrzebujesz prezentacji ani dokumentacji — wystarczy problem, cel albo przykład obecnego procesu.", calendlyCta: "Umów rozmowę o aplikacji", form: { title: "Opisz, co chcesz zmienić", intro: "Jedno lub dwa zdania wystarczą na start.", messageLabel: "Co użytkownik lub pracownik powinien móc zrobić łatwiej?", messagePlaceholder: "Na przykład: klienci dzwonią, żeby umówić termin i sprawdzić status, a chcemy dać im samoobsługowy portal.", submit: "Wyślij opis pomysłu" }, cta: "Opowiedz, co aplikacja ma zmienić", stickyCta: "Opowiedz o aplikacji" },
} as const;

describe("service sales content contract", () => {
  it("uses only the approved canonical proof slug order", () => {
    expect(serviceSales.core.proof.caseSlugs).toEqual(["public-sector-poland", "public-sector-eu"]);
    expect(serviceSales.automation.proof.caseSlugs).toEqual(["localhost-academy"]);
    expect(serviceSales.web.proof.caseSlugs).toEqual(["international-automotive-sales-platform", "enterprise-30-years-in-production"]);
    expect(serviceSales.core.proof).not.toHaveProperty("cards");
    expect(serviceSales.automation.proof).not.toHaveProperty("cards");
    expect(serviceSales.web.proof).not.toHaveProperty("cards");
  });

  it("matches every approved field for exactly three redesigned funnels", () => {
    const plain = JSON.parse(JSON.stringify(serviceSales), (_key, value) => typeof value === "string" ? stripEmphasis(value) : value);
    expect(plain).toEqual({ core: coreExpected, automation: automationExpected, web: webExpected });
    expect(Object.keys(serviceSales).sort()).toEqual(["automation", "core", "web"]);
    expect("legacy" in serviceSales).toBe(false);
    expect(serviceSalesUi).toEqual({ demoRegion: "Przegląd dem", nextDemo: "Następne demo", previousDemo: "Poprzednie demo", proposal: "Propozycja rozwiązania" });
  });

  it("keeps every emphasis marker pair balanced", () => {
    const strings: string[] = [];
    const collect = (value: unknown) => {
      if (typeof value === "string") strings.push(value);
      else if (Array.isArray(value)) value.forEach(collect);
      else if (value && typeof value === "object") Object.values(value).forEach(collect);
    };
    collect(serviceSales);
    for (const text of strings) {
      expect(text.split("**").length % 2, `unbalanced ** in: ${text}`).toBe(1);
    }
  });

  it("matches the approved headline, teaser, challenge, approach and results for five proof cases", () => {
    const expected = {
      "public-sector-poland": { headline: "Jedna platforma dla 20 administracji miejskich", teaser: "Około 20 tys. osób korzysta z jednego miejsca do obsługi spraw pracowniczych. Platforma uwzględnia różnice między miastami i wymienia dane ze starszym systemem kadrowo-płacowym.", challenge: "Każde miasto pracuje trochę inaczej, ale wszystkie korzystają z jednej platformy. System musiał obsługiwać różne zasady i jednocześnie wymieniać dane o czasie pracy, nieobecnościach i wypłatach ze starszym rozwiązaniem kadrowo-płacowym.", approach: "Przejąłem odpowiedzialność za architekturę działającej platformy. Uprościłem sposób włączania funkcji dla poszczególnych miast i zbudowałem brakujące połączenie z systemem kadrowo-płacowym — od projektu po wdrożenie.", results: "Platforma działa w 20 administracjach miejskich i obsługuje około 20 tys. użytkowników. Konfiguracja kolejnego miasta nie wymaga już wiedzy eksperckiej, a nowa integracja weszła do oferty handlowej produktu." },
      "e-delivery-platform-nationwide": { headline: "Około 2,5 mln plików przeniesionych bez utraty danych", teaser: "Migrację podzieliłem na bezpieczne, możliwe do wznowienia etapy. Każdy z nich potwierdzał kompletność danych, a finałowe przełączenie zakończyło się w jeden weekend.", challenge: "Regulowana platforma dokumentowa musiała przenieść około 2,5 mln plików, czyli blisko 500 GB danych. Utrata nawet części dokumentów oznaczałaby konsekwencje wykraczające poza zwykłą awarię techniczną.", approach: "Zaprojektowałem i zbudowałem proces, który można było zatrzymać, sprawdzić i bezpiecznie wznowić. Każdy etap zapisywał postęp i kontrolował zgodność przeniesionych danych.", results: "Wszystkie pliki zostały przeniesione bez utraty danych. Migrację można było prowadzić etapami, a jej końcowy przebieg produkcyjny zamknął się w jednym weekendzie." },
      "localhost-academy": { headline: "Codzienna obsługa szkoły bez dokładania ręcznej administracji", teaser: "Automatyzacje wspierają płatności, komunikację, przypomnienia, notatki i onboarding. Korzysta z nich 150–200 uczniów, pracowników i osób zarządzających dziennie.", challenge: "Szkoła prowadzi mentoring jeden na jeden, dlatego każde administracyjne przeoczenie bezpośrednio wpływa na doświadczenie ucznia. Płatności, komunikacja, przypomnienia i onboarding były obsługiwane ręcznie, a wraz ze wzrostem szkoły zabierały coraz więcej czasu.", approach: "Zamiast budować kosztowny system od zera, wykorzystałem narzędzia, które organizacja już znała: Make, Airtable, Notion, Discord i usługi Google. Zaprojektowałem cały przepływ i poprowadziłem wdrożenie realizowane wspólnie z dwoma inżynierami.", results: "Z automatyzacji korzysta codziennie 150–200 osób. Powtarzalna administracja nie ogranicza już w takim stopniu liczby obsługiwanych uczniów, a zespół może samodzielnie zmieniać część reguł bez edycji kodu." },
      "enterprise-30-years-in-production": { headline: "Nowoczesna platforma bez zatrzymywania działającego systemu", teaser: "Rdzeń systemu obsługującego około 20 tys. użytkowników został przeniesiony na współczesną platformę webową w mniej niż rok i bez nieplanowanych przestojów.", challenge: "System działał od dekad i nadal był potrzebny około 20 tys. użytkowników. Starzejąca się technologia utrudniała rozwój i utrzymanie, ale jednorazowe przepisanie całości stwarzało zbyt duże ryzyko dla działającego biznesu.", approach: "Pracując w zespole, współtworzyłem kierunek stopniowej migracji. Nowa platforma powstawała obok istniejącego systemu, dzięki czemu kolejne elementy można było wymieniać bez zatrzymywania codziennej pracy.", results: "Migracja rdzenia została dostarczona w mniej niż rok, bez nieplanowanych przestojów. Użytkownicy otrzymali nowoczesny interfejs, a system stał się prostszy w utrzymaniu i gotowy na kolejne integracje." },
      "public-sector-eu": { headline: "Integracja e-doręczeń zweryfikowana na 50 tys. użytkowników na godzinę", teaser: "Warstwa integracyjna połączyła systemy krajowe i transgraniczne, zachowując wymagania bezpieczeństwa, weryfikowalności i zgodności prawnej.", challenge: "Każda wiadomość w systemie e-doręczeń ma znaczenie prawne. Platforma musiała połączyć wiele zewnętrznych systemów działających według różnych standardów, bez osłabienia bezpieczeństwa i możliwości potwierdzenia przebiegu doręczenia.", approach: "Jako członek zespołu współtworzyłem usługi odpowiedzialne za wymianę danych z systemami zewnętrznymi. Bezpieczeństwo, zgodność i zakładane obciążenie były uwzględniane na każdym etapie projektu.", results: "Warstwa integracyjna została zaprojektowana i zweryfikowana dla obciążenia 50 tys. użytkowników na godzinę. Powstała infrastruktura przygotowana do obsługi usługi o ogólnokrajowej skali." },
    } as const;
    for (const [slug, copy] of Object.entries(expected)) {
      const item = getCaseBySlug(slug);
      expect(item).toBeDefined();
      expect({ headline: item?.headline, teaser: item?.teaser, challenge: item?.challenge, approach: item?.approach, results: item?.results }).toEqual(copy);
    }
  });

  it("keeps approved campaign metadata exact", () => {
    const metadata = (slug: string) => { const service = getServiceBySlug(slug); return { metaTitle: service?.metaTitle, metaDescription: service?.metaDescription }; };
    expect(metadata("systemy-i-integracje")).toEqual({ metaTitle: "Integracje ERP ze sklepem i marketplace | calm_soft", metaDescription: "Łączę Comarch, Subiekt, enova i WAPRO ze sklepami, marketplace, KSeF i systemami partnerów. Bez ręcznego przepisywania danych i ciągłych rozjazdów." });
    expect(metadata("automatyzacja")).toEqual({ metaTitle: "Automatyzacja procesów w firmie | calm_soft", metaDescription: "Automatyzuję faktury, dokumenty, raportowanie, onboarding i przepływ danych. Zaczynam od jednego procesu i sprawdzam, czy wdrożenie się opłaca." });
    expect(metadata("platformy-webowe")).toEqual({ metaTitle: "Aplikacje i platformy webowe na zamówienie | calm_soft", metaDescription: "Projektuję i buduję portale klienta, panele pracowników, systemy rezerwacji i produkty online. Od celu biznesowego po działające wdrożenie." });
  });
});
