import type { SiteContent } from "./types";

export const site: SiteContent = {
  name: "calm_soft",
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "hello@calmsoft.com",
  eyebrow: "Systemy centralne · Integracje · Automatyzacja · Ratowanie legacy",
  navCta: "Zacznij projekt",
  featuredCaseSlugs: [
    "public-sector-poland",
    "e-delivery-platform-nationwide",
    "localhost-academy",
  ],
  featuredDemoSlugs: ["cadence", "airlift", "healthlab"],
  footerLinks: [
    { label: "Usługi", href: "/#services" },
    { label: "Realizacje", href: "/#cases" },
    { label: "Dema", href: "/#demo" },
    { label: "Proces", href: "/#process" },
    { label: "Cennik", href: "/pricing/" },
    { label: "Kontakt", href: "/#contact" },
  ],
  hero: {
    aurora: {
      h1: "Oprogramowanie, które\npo prostu działa.",
      lead: "Platformy webowe, automatyzacja, integracje i ratowanie legacy — budowane od początku do końca przez osobę, która traktuje Twój produkt jak własny.",
      ctaPrimary: "Zacznij projekt",
      ctaSecondary: "Poznaj usługi",
    },
    code: {
      h1: "Spokojna strona oprogramowania.",
      lead: "Systemy klasy enterprise bez enterprise'owej dramy — jasny proces, uczciwe terminy i żadnych niespodzianek w czwartym miesiącu. Od pierwszej rozmowy do produkcji rozmawiasz z inżynierem, który pisze kod — dziś jedynym architektem platformy używanej w dwudziestu administracjach miejskich.",
      ctaPrimary: "Zacznij projekt",
      ctaDemos: "Zobacz dema ›",
      ctaPricing: "Sprawdź cennik ›",
      demoLabel: "Dema na żywo",
    },
    type: {
      line1: "Złożone problemy.",
      line2: "Spokojny software.",
      lead: "Od platform webowych i automatyzacji po integracje i ratowanie legacy — dowożone przez osobę, która dotrzymuje obietnic.",
      ctaPrimary: "Zacznij projekt",
    },
  },
  sections: {
    services: {
      line1: "Cztery obszary.",
      line2: "Jeden inżynier odpowiedzialny za całość.",
      pricingCta: "Zobacz przejrzysty cennik ›",
      pricingPrompt: "Zastanawiasz się, ile kosztuje taki projekt?",
      sliderLabel: "Przegląd usług",
      overviewLabel: "Przegląd usługi",
      fitLabel: "Kiedy to właściwy wybór",
      deliverLabel: "Co dostarczam",
      approachLabel: "Jak to prowadzę",
      proofLabel: "Dowody z realizacji",
      readCaseCta: "Przeczytaj historię ›",
      cta: "Omówmy taki projekt ›",
      note: "Odpowiadam w ciągu godziny w dni robocze · NDA na życzenie.",
    },
    process: { line1: "Od pomysłu do produkcji.", line2: "Spokojnie, krok po kroku." },
    cases: {
      line1: "Dowody, nie obietnice.",
      line2: "Praca, która działa na produkcji.",
      intro: [
        "Od automatyzacji zaplecza szkoły programowania w Lublinie po platformy działające w administracjach miejskich — te same standardy, inna skala.",
        "Wszystko poniżej działa na produkcji. Nie prototypy, nie piloty — żywe systemy, na których ludzie codziennie polegają.",
      ],
      footnote: "Tam, gdzie wymagają tego umowy o poufności, nazwy klientów pomijam. O szczegółach chętnie opowiem na rozmowie.",
      seeAllCta: "Zobacz wszystkie case studies ›",
      calendly: {
        prompt: "Wolisz omówić swój projekt na żywo?",
        cta: "Umów bezpłatną rozmowę (30 min) ›",
      },
    },
    demos: {
      line1: "Działający software, nie slajdy.",
      line2: "Klikalne dema od początku do końca.",
      langChip: "Interfejs po angielsku",
      cta: "Otwórz demo ›",
      footnote: "W pełni klikalne — przejdź każdy przepływ tak, jak zrobiłby to prawdziwy użytkownik.",
      seeAllCta: "Zobacz wszystkie dema ›",
      detailCta: "Zobacz szczegóły ›",
      liveCta: "Otwórz demo na żywo ›",
      techLegend: "Technologie, w których mogę to zbudować",
      flowsLegend: "Kluczowe przepływy",
      desktopNote: "Panel back-office — zbudowany pod desktop, nieadaptowany do mobile.",
      calendly: {
        prompt: "Demo przeklikane — chcesz takie u siebie?",
        cta: "Umów bezpłatną rozmowę (30 min) ›",
      },
    },
  },
  modals: {
    caseNote: "Nazwy klientów pomijam tam, gdzie wymaga tego poufność — szczegóły chętnie na rozmowie.",
    demoNote: "W pełni klikalny prototyp — zbudowany zgodnie z dobrymi praktykami, gotowy stać się prawdziwym produktem.",
  },
  contact: {
    heading: "Zbudujmy coś, co zostanie.",
    paragraph: "Opowiedz mi o swoim projekcie. Odpisze Ci inżynier, który wykonałby tę pracę — nie skrypt sprzedażowy.",
    checks: [
      "Odpowiedź w ciągu godziny w dni robocze — ode mnie, nie z autorespondera",
      "NDA na życzenie — Twój pomysł zostaje Twój",
      "Działam z Polski, w całej UE — na miejscu lub zdalnie",
    ],
    talk: {
      title: "Wolisz najpierw porozmawiać?",
      body: "Umów bezpłatną, 30-minutową rozmowę ze mną. Bez pitchu i slajdów — konkretna rozmowa o tym, co budujesz.",
      cta: "Umów bezpłatną rozmowę (30 min) ›",
    },
    form: {
      title: "Opowiedz mi o projekcie",
      intro: "Dwa pola i jedno zdanie w zupełności wystarczą na start. Odpowiadam w ciągu godziny w dni robocze.",
      fields: {
        name: "Imię i nazwisko",
        email: "E-mail",
        message: "Co chcesz zbudować albo naprawić?",
      },
      messagePlaceholder: "Wystarczy zdanie lub dwa. Jaka jest sytuacja i co by znaczyło „rozwiązane\"?",
      submit: "Wyślij do mnie",
      submitting: "Wysyłam…",
      fieldErrors: {
        name: "Podaj swoje imię.",
        emailRequired: "Podaj adres e-mail.",
        emailInvalid: "Podaj poprawny adres e-mail.",
        message: "Napisz choć zdanie o projekcie.",
      },
      submitError: "Coś poszło nie tak i wiadomość nie została wysłana. Spróbuj ponownie — albo napisz do mnie bezpośrednio mailem.",
      finePrint: "Odpowiadam w ciągu godziny w dni robocze · NDA na życzenie",
      success: {
        heading: "Wysłane.",
        paragraph: "Dzięki — to już wystarczy, żebym odpisał. Chcesz przyspieszyć? Możesz dorzucić kilka opcjonalnych szczegółów:",
        again: "Wyślij kolejne zapytanie ›",
        details: {
          areaLegend: "Który obszar najbliżej?",
          areaOptions: [
            { id: "core", label: "Systemy centralne" },
            { id: "automation", label: "Automatyzacja" },
            { id: "rescue", label: "Ratowanie legacy" },
            { id: "web", label: "Platforma webowa" },
            { id: "not-sure", label: "Jeszcze nie wiem" },
          ],
          budgetLegend: "Orientacyjny budżet?",
          budgetOptions: [
            { id: "under-10k", label: "Do 10 tys. zł" },
            { id: "10-30k", label: "10–30 tys. zł" },
            { id: "30-80k", label: "30–80 tys. zł" },
            { id: "80k-plus", label: "80 tys. zł +" },
            { id: "no-idea", label: "Jeszcze nie wiem" },
          ],
          phoneLabel: "Telefon — jeśli wolisz, żebym zadzwonił (opcjonalnie)",
          phoneInvalid: "Podaj poprawny numer telefonu albo zostaw pole puste.",
          submit: "Dodaj szczegóły ›",
          submitting: "Wysyłam…",
          skip: "Albo po prostu czekaj na mój e-mail — jedno i drugie działa.",
          done: "Dzięki, mam wszystko. Odezwę się wkrótce.",
          error: "Nie udało się wysłać szczegółów — ale spokojnie, Twoje zapytanie już do mnie dotarło.",
        },
      },
    },
  },
  work: {
    metaTitle: "Case studies — calm_soft",
    metaDescription:
      "Wszystkie realizacje calm_soft w jednym miejscu — ratowanie legacy, platformy sektora publicznego, migracja 2,5 mln plików i automatyzacje. Każda z liczbami.",
    heading: { line1: "Każdy projekt,", line2: "z liczbami." },
    lead: "Wszystkie realizacje w jednym miejscu — prawdziwe systemy, prawdziwa skala i liczby, które obronię na rozmowie.",
    calendly: {
      prompt: "Widzisz coś bliskiego Twojemu projektowi?",
      cta: "Umów bezpłatną rozmowę (30 min) ›",
    },
    startLabel: "Zacznij projekt ›",
    archiveHeading: "Archiwum",
    archiveIntro: "Starsza praca zespołowa — zostaje dla pełnego obrazu, choć dziś moją miarą są projekty, które prowadzę w całości.",
  },
  demosPage: {
    metaTitle: "Dema — calm_soft",
    metaDescription:
      "Siedem klikalnych dem calm_soft — strony klinik, konsole personelu oraz narzędzia automatyzacji i migracji danych. Każde zbudowane zgodnie z dobrymi praktykami.",
    heading: { line1: "Siedem dem,", line2: "klikalnych od A do Z." },
    lead: "Strony klinik dla pacjentów, konsole personelu za nimi oraz narzędzia automatyzacji i migracji — każde demo w pełni klikalne, zbudowane tak, jak zbudowałbym prawdziwy produkt.",
    calendly: {
      prompt: "Chcesz takie rozwiązanie skrojone pod swój biznes?",
      cta: "Umów bezpłatną rozmowę (30 min) ›",
    },
    startLabel: "Zacznij projekt ›",
  },
  notFound: {
    heading: "Nic tu nie ma.",
    text: "Ta strona nie istnieje — ale Twój projekt może.",
    back: "Wróć na stronę główną ›",
  },
  consent: {
    text: "Używam Google Analytics i mierzę skuteczność reklam Google Ads, żeby wiedzieć, które treści działają. Te cookies włączą się tylko za Twoją zgodą.",
    accept: "Akceptuję",
    decline: "Odrzucam",
    settingsLabel: "Ustawienia cookies",
  },
};
